org.gradle.java.home=C:/AndroidStudioJBR
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefParsingEnabled -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
android.useAndroidX=true
android.disallowKotlinSourceSets=false
android.nonTransitiveRClass=false
APP_VERSION_CODE=9
APP_VERSION_NAME=0.7.5-beta
